apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "snowplow.fullname" . }}-{{ .Release.Namespace }}
  labels:
    {{- include "snowplow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - core.krateo.io
  resources:
  - compositiondefinitions
  - schemadefinitions
  verbs:
  - get
  - list
- apiGroups:
  - templates.krateo.io
  resources:
  - "*"
  verbs:
  - get
  - list
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - secrets
  verbs:
  - get
  - list