apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snowplow.fullname" . }}-jq-custom-modules
  labels:
  {{- include "snowplow.labels" . | nindent 4 }}
data:
  custom.jq: |
{{ tpl (.Files.Get "assets/custom-modules.jq") . | indent 4 }}